version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/hhru2
      dockerfile: Dockerfile
    ports:
      - "80:80"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: hesh
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
